# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/unary.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/unary.proto\x12\x05proto\"\x14\n\x04Size\x12\x0c\n\x04size\x18\x01 \x01(\x03\"\x15\n\x05\x45mpty\x12\x0c\n\x04send\x18\x01 \x01(\x08\"\x1d\n\nnewElement\x12\x0f\n\x07\x65lement\x18\x01 \x01(\t\"\x1c\n\x08Received\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\xad\x01\n\x0cQueueService\x12)\n\x03put\x12\x11.proto.newElement\x1a\x0f.proto.Received\x12\'\n\x04pick\x12\x0c.proto.Empty\x1a\x11.proto.newElement\x12&\n\x03pop\x12\x0c.proto.Empty\x1a\x11.proto.newElement\x12!\n\x04size\x12\x0c.proto.Empty\x1a\x0b.proto.Sizeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.unary_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIZE._serialized_start=28
  _SIZE._serialized_end=48
  _EMPTY._serialized_start=50
  _EMPTY._serialized_end=71
  _NEWELEMENT._serialized_start=73
  _NEWELEMENT._serialized_end=102
  _RECEIVED._serialized_start=104
  _RECEIVED._serialized_end=132
  _QUEUESERVICE._serialized_start=135
  _QUEUESERVICE._serialized_end=308
# @@protoc_insertion_point(module_scope)
