# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import unary_pb2 as proto_dot_unary__pb2


class QueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.put = channel.unary_unary(
                '/proto.QueueService/put',
                request_serializer=proto_dot_unary__pb2.newElement.SerializeToString,
                response_deserializer=proto_dot_unary__pb2.Received.FromString,
                )
        self.pick = channel.unary_unary(
                '/proto.QueueService/pick',
                request_serializer=proto_dot_unary__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_unary__pb2.newElement.FromString,
                )
        self.pop = channel.unary_unary(
                '/proto.QueueService/pop',
                request_serializer=proto_dot_unary__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_unary__pb2.newElement.FromString,
                )
        self.size = channel.unary_unary(
                '/proto.QueueService/size',
                request_serializer=proto_dot_unary__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_unary__pb2.Size.FromString,
                )


class QueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def size(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'put': grpc.unary_unary_rpc_method_handler(
                    servicer.put,
                    request_deserializer=proto_dot_unary__pb2.newElement.FromString,
                    response_serializer=proto_dot_unary__pb2.Received.SerializeToString,
            ),
            'pick': grpc.unary_unary_rpc_method_handler(
                    servicer.pick,
                    request_deserializer=proto_dot_unary__pb2.Empty.FromString,
                    response_serializer=proto_dot_unary__pb2.newElement.SerializeToString,
            ),
            'pop': grpc.unary_unary_rpc_method_handler(
                    servicer.pop,
                    request_deserializer=proto_dot_unary__pb2.Empty.FromString,
                    response_serializer=proto_dot_unary__pb2.newElement.SerializeToString,
            ),
            'size': grpc.unary_unary_rpc_method_handler(
                    servicer.size,
                    request_deserializer=proto_dot_unary__pb2.Empty.FromString,
                    response_serializer=proto_dot_unary__pb2.Size.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.QueueService/put',
            proto_dot_unary__pb2.newElement.SerializeToString,
            proto_dot_unary__pb2.Received.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.QueueService/pick',
            proto_dot_unary__pb2.Empty.SerializeToString,
            proto_dot_unary__pb2.newElement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.QueueService/pop',
            proto_dot_unary__pb2.Empty.SerializeToString,
            proto_dot_unary__pb2.newElement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def size(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.QueueService/size',
            proto_dot_unary__pb2.Empty.SerializeToString,
            proto_dot_unary__pb2.Size.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
